// Package scaffold provides code generation from Go struct tag Kind definitions.
// The Generate function scaffolds new projects from templates; the GenerateFromKinds
// function reads parsed KindDef values and produces Go types, TypeScript interfaces,
// and K8s resource registration code — the same outputs that CUE-based generation
// would produce, but driven entirely by annotated Go structs.
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// GenerateFromKinds reads parsed Kind definitions and writes generated code to outDir.
// It produces:
//   - Go types and registration helpers (kinds/<lower>.gen.go)
//   - TypeScript interfaces (kinds/<lower>.gen.ts)
//   - A resource registration snippet (kinds/register.gen.go)
func GenerateFromKinds(kinds []KindDef, outDir string) ([]string, error) {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return nil, fmt.Errorf("mkdir %s: %w", outDir, err)
	}

	var written []string

	for _, k := range kinds {
		lower := strings.ToLower(k.Name)

		// Go generated types
		goPath := filepath.Join(outDir, lower+".gen.go")
		if err := writeGenTemplate(goPath, tmplGenGo, k); err != nil {
			return written, fmt.Errorf("generate %s: %w", goPath, err)
		}
		written = append(written, goPath)

		// TypeScript interfaces
		tsPath := filepath.Join(outDir, lower+".gen.ts")
		if err := writeGenTemplate(tsPath, tmplGenTS, k); err != nil {
			return written, fmt.Errorf("generate %s: %w", tsPath, err)
		}
		written = append(written, tsPath)
	}

	// Registration file that registers all kinds
	regPath := filepath.Join(outDir, "register.gen.go")
	if err := writeGenTemplate(regPath, tmplGenRegister, kinds); err != nil {
		return written, fmt.Errorf("generate %s: %w", regPath, err)
	}
	written = append(written, regPath)

	return written, nil
}

func writeGenTemplate(path, tmplStr string, data interface{}) error {
	funcMap := template.FuncMap{
		"lower":    strings.ToLower,
		"plural":   func(s string) string { return strings.ToLower(s) + "s" },
		"group":    func(s string) string { return strings.ToLower(s) + "s.grafana.app" },
		"tsType":   goTypeToTS,
		"optional": func(f FieldDef) bool { return !f.Required },
	}
	t, err := template.New(filepath.Base(path)).Funcs(funcMap).Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return t.Execute(f, data)
}

func goTypeToTS(goType string) string {
	switch goType {
	case "string":
		return "string"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return "number"
	case "bool":
		return "boolean"
	}
	if strings.HasPrefix(goType, "[]") {
		return goTypeToTS(goType[2:]) + "[]"
	}
	if strings.HasPrefix(goType, "map[") {
		return "Record<string, unknown>"
	}
	return "unknown"
}

// --- Generated Go types template ---

const tmplGenGo = `// Code generated by grafana-app-sdk generate; DO NOT EDIT.
package kinds

import (
	"github.com/grafana/grafana-app-sdk/quickstart/local"
)

// {{.Name}}Spec is the generated spec type for the {{.Name}} Kind.
{{- if .Description}}
// {{.Description}}
{{- end}}
type {{.Name}}Spec struct {
{{- range .Fields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.JSONName}}{{if .Omitempty}},omitempty{{end}}"{{if .Description}} description:"{{.Description}}"{{end}}{{if .Required}} validate:"required"{{end}}` + "`" + `
{{- end}}
}

// {{.Name}}Description is the human-readable description for the {{.Name}} Kind.
// Used by MCP tool generators to produce agent-friendly tool descriptions.
const {{.Name}}Description = "{{.Description}}"

// {{.Name}}Resource returns the GroupVersionResource for {{.Name}}.
func {{.Name}}Resource() local.GroupVersionResource {
	return local.GroupVersionResource{
		Group:    "{{if .Group}}{{.Group}}{{else}}{{lower .Name}}s.grafana.app{{end}}",
		Version:  "{{.Version}}",
		Resource: "{{plural .Name}}",
		Kind:     "{{.Name}}",
	}
}
`

// --- Generated TypeScript template ---

const tmplGenTS = `// Code generated by grafana-app-sdk generate; DO NOT EDIT.
{{- if .Description}}

/** {{.Description}} */
{{- end}}
export interface {{.Name}}Spec {
{{- range .Fields}}
  {{.JSONName}}{{if optional .}}?{{end}}: {{tsType .GoType}};
{{- end}}
}

export interface {{.Name}} {
  apiVersion: string;
  kind: '{{.Name}}';
  metadata: {
    name: string;
    namespace: string;
    resourceVersion?: string;
    labels?: Record<string, string>;
    creationTimestamp?: string;
  };
  spec: {{.Name}}Spec;
  status?: Record<string, unknown>;
}

export interface {{.Name}}List {
  apiVersion: string;
  kind: '{{.Name}}List';
  items: {{.Name}}[];
}
`

// --- Registration helper template ---

const tmplGenRegister = `// Code generated by grafana-app-sdk generate; DO NOT EDIT.
package kinds

import (
	"github.com/grafana/grafana-app-sdk/quickstart/local"
)

// RegisterAll registers all generated Kinds on the given server.
func RegisterAll(srv *local.Server) {
{{- range .}}
	srv.RegisterResource({{.Name}}Resource())
{{- end}}
}
`
